//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.07 at 02:19:19 PM CEST 
//


package de.hpi.bpmn2_0.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for tFlowNode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tFlowNode">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/bpmn20}tFlowElement">
 *       &lt;sequence>
 *         &lt;element name="incoming" type="{http://www.w3.org/2001/XMLSchema}QName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="outgoing" type="{http://www.w3.org/2001/XMLSchema}QName" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tFlowNode", propOrder = {
    "incoming",
    "outgoing"
})
@XmlSeeAlso({
    Event.class,
//    TChoreographyActivity.class,
    Gateway.class,
    Activity.class
})
public abstract class FlowNode
    extends FlowElement
{

    protected List<FlowNode> incoming;
    protected List<FlowNode> outgoing;
    
    /**
     * Convenience method to retrieve all incoming {@link SequenceFlow}
     * 
     * Changes to that list have no influence to the result other callers get.
     * 
     * @return The list of {@link SequenceFlow}
     */
    public List<SequenceFlow> getIncomingSequenceFlows() {
    	ArrayList<SequenceFlow> incomingSeq = new ArrayList<SequenceFlow>();
    	
    	for(FlowNode node : this.getIncoming()) {
    		/* Determine if type of sequence flow */
    		if(node instanceof SequenceFlow) {
    			incomingSeq.add((SequenceFlow) node);
    		}
    	}
    	
    	return incomingSeq;
    }
    
    /**
     * Convenience method to retrieve all outgoing {@link SequenceFlow}
     * 
     * Changes to that list have no influence to the result other callers get.
     * 
     * @return The list of {@link SequenceFlow}
     */
    public List<SequenceFlow> getOutgoingSequenceFlows() {
    	ArrayList<SequenceFlow> outgoingSeq = new ArrayList<SequenceFlow>();
    	
    	for(FlowNode node : this.getOutgoing()) {
    		/* Determine if type of sequence flow */
    		if(node instanceof SequenceFlow) {
    			outgoingSeq.add((SequenceFlow) node);
    		}
    	}
    	
    	return outgoingSeq;
    }
    
    /* Getters */
    
    /**
     * Gets the value of the incoming property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the incoming property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncoming().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QName }
     * 
     * 
     */
    public List<FlowNode> getIncoming() {
        if (incoming == null) {
            incoming = new ArrayList<FlowNode>();
        }
        return this.incoming;
    }

    /**
     * Gets the value of the outgoing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outgoing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutgoing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QName }
     * 
     * 
     */
    public List<FlowNode> getOutgoing() {
        if (outgoing == null) {
            outgoing = new ArrayList<FlowNode>();
        }
        return this.outgoing;
    }

}
